name = "young-web-shot"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".next"

[env.production]
name = "young-web-shot"

[env.preview]
name = "young-web-shot-preview"