name = "young-web-shot"
compatibility_date = "2024-06-02"
compatibility_flags = ["nodejs_compat"]
browser = { binding = "MYBROWSER" }
account_id = "e53afad7d4c6c735db4b50a7a5a51810"

# 自定义域名路由
routes = [
  { pattern = "webshot.darkchoco.top", custom_domain = true }
]

# Worker 脚本入口
main = "worker.js"

# 环境变量
[vars]
NODE_ENV = "production"
# Bark 推送配置 (可选)
# 格式: https://api.day.app/YOUR_KEY
BARK_URL = "https://bark.darkchoco.top/tAJWRkmn9PeDsyqUZ4ceK3"


# 日志观察配置
[observability.logs]
enabled = true