name = "young-web-shot"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Worker 脚本入口
main = "worker.js"

# 环境变量
[vars]
NODE_ENV = "production"
account_id = "e53afad7d4c6c735db4b50a7a5a51810"

#[browser]
#binding = "MYBROWSER"

browser = { binding = "MYBROWSER" }


# 日志观察配置
[observability.logs]
enabled = true